# Welcome to Jekyll!

# Website settings
title: "NOFETAN INC."
description: "주식회사 노페땅"
keywords: "노페땅, 삼천원"
baseurl: "/"
url: "http://nofetan.com"

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# landing page
landing:
  home: home
  about: about
  history: history
  team: team
  blog: blog
  contact: contact

#landing:
#  home: landing-1
#  about: landing-2
#  career: landing-3
#  skills: landing-4
#  projects: landing-5
#  blog: landing-6
#  link: landing-7

# my projects
member:
  kkt:
    name: '김경태'
    img: 'static/img/landing/kkt.png'
    description: '멤버에 대한 소개'
  kms:
    name: '김민식'
    img: 'static/img/landing/kms.png'
    description: '클래식 음악과 교토 애니메이션을 좋아합니다.'
  kmg:
    name: 'mango'
    img: 'static/img/landing/kmg.png'
    description: '멤버에 대한 소개'
  ksy:
    name: '김서영'
    img: 'static/img/landing/ksy.png'
    description: 'AMAZING☆'
  rs:
    name: '류석'
    img: 'static/img/landing/rs.png'
    description: '멤버에 대한 소개'
  rch:
    name: '류창현'
    img: 'static/img/landing/rch.png'
    description: '발라 모굴리스'
  pjh:
    name: 'pjhjohn'
    img: 'static/img/landing/pjh.png'
    description: '서비스는 죽지 않아요. 대가를 치를 뿐.'
  syk:
    name: '서영광'
    img: 'static/img/landing/syk.png'
    description: '키랏~☆ 리라메루 라라메루 란 루라 란'
  ljh:
    name: '이지호'
    img: 'static/img/landing/ljh.png'
    description: '지나가던 잡덕 1입니다.'
  cdh:
    name: '장동현'
    img: 'static/img/landing/cdh.png'
    description: '멤버에 대한 소개'
  cgr:
    name: '최가람'
    img: 'static/img/landing/cgr.png'
    description: '멤버에 대한 소개'

# blog index
index:
  home: home
  dev: dev
  press: press

# donate
# donate:
#  wechat: 'static/img/pay/wechat.png'
#  alipay: 'static/img/pay/alipay.png'

# comment
# changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: nofetan-com
  public_key: dAHG9O5ctrGdGqOzT5GGqYFMsCgiT1NioZDqS9eoyseMS9xGGhu2IuEY4IFsoJAL

# share
#bshare:
#  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
#ba:
#  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-77708429-2

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
